services:
  app:
    image: thomasjiitak/learn:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000" # NGINX will listen on this port
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
