name: Docker Image CI-CD dev
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: thomasjiitak/learn:latest
jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildxocke
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ${{env.IMAGE_NAME}}
          cache-from: type=registry,ref=${{env.IMAGE_NAME}}
          cache-to: type=inline
          platforms: linux/arm64