name: Docker Image CI-CD dev
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: thomasjiitak/learn:latest
jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildxocke
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ${{env.IMAGE_NAME}}
          cache-from: type=registry,ref=${{env.IMAGE_NAME}}
          cache-to: type=inline
          platforms: linux/arm64

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add Target Machine to Known Hosts
        run: |
          ssh-keyscan -H 100.108.157.41 >> ~/.ssh/known_hosts

      - name: SSH and run commands
        run: |
          ssh -o StrictHostKeyChecking=no shyamsankarkr@100.108.157.41 "echo 'SSH connection successful'"