name: Docker Image CI-CD dev
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: thomasjiitak/learn:latest
jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildxocke
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ${{env.IMAGE_NAME}}
          cache-from: type=registry,ref=${{env.IMAGE_NAME}}
          cache-to: type=inline
          platforms: linux/arm64

      - name: Remote Docker Runner
        uses: thomasvjoseph/remote-docker-runner-action@v1.0.0-rc7.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          image: thomasjiitak/learn
          container_name: test-app
          docker_username: ${{secrets.DOCKER_USERNAME}}
          docker_password: ${{secrets.DOCKER_PASSWORD}}