name: Docker Image CI-CD dev
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: thomasjiitak/learn:latest
  KEY: ${{ vars.KEY }}
  PASSWORD: ${{ vars.PASSWORD }}
jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      issues: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildxocke
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ${{env.IMAGE_NAME}}
          cache-from: type=registry,ref=${{env.IMAGE_NAME}}
          cache-to: type=inline

      - name: Remote Docker Runner
        uses: thomasvjoseph/ssh-docker@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          image: thomasjiitak/learn
          container_name: test-app
          docker_username: ${{secrets.DOCKER_USERNAME}}
          docker_password: ${{secrets.DOCKER_PASSWORD}}
          docker_ports: "-p 80:80"
          env_vars: |
            - KEY=${{ vars.KEY }}
            - PASSWORD=${{ vars.PASSWORD }}